name: Docker and EKS Deploy

on:
  release:
    types:
      - created

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t master099/DevOpsPy:${{ github.event_name }} .

      - name: Push Docker Image
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push master099/DevOpsPy:${{ github.event_name }}

      # - name: Configure AWS Credentials
      #   run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} && aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} && aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

      # - name: Deploy to AWS EKS
      #   run: |
      #     eksctl create cluster --name your-eks-cluster-name --version 1.21 --region ${{ secrets.AWS_DEFAULT_REGION }} --nodegroup-name standard-workers --node-type t2.micro --nodes 2 --nodes-min 1 --nodes-max 3 --node-ami auto

      #     kubectl apply -f your-k8s-manifest.yaml
